server:
  port: 9000

spring:
  main:
    banner-mode: off
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: schambeck-admin
      password: pass
    realmImportFile: schambeck-realm.json
