version: '3.9'
services:
  web:
    image: srv-authorization:latest
    networks:
      - schambeck-net
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
    ports:
      - target: 9000
        published: 9000
networks:
  schambeck-net:
    external: true
